### ISSUE TITLE
Delete unnecessary commented lines

### ISSUE THREAD

**Issue by mjmaher987** [MOH-Shafizadegan/Gstreamer-Sox#1]
https://github.com/MOH-Shafizadegan/Gstreamer-Sox/blob/085e39717bd4c0f75b372ce62d798a8f069f2dcd/app.py#L39

I suggest to delete unnecessary comments, and add some guiding comments to the code.
Also the code structure can be refined.

**Comment by MOH-Shafizadegan** [comment]
Thanks for you feedback!
I will consider this.
